server:
  port: 7002
eureka:
  client:
    service-url:
     #defaultZone: http://localhost:7001/eureka
     defaultZone: http://eureka7000.com:7000/eureka/,http://eureka7001.com:7001/eureka/,http://eureka6999.com:6999/eureka/
  instance:
    instance-id: provider-7002
    prefer-ip-address: false #访问路径可以显示IP地址
spring:
  application:
    name: provider-7002