server:
  port: 6999

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: host1 #eureka服务端的实例名称
  client:
    register-with-eureka: true #false 表示不向注册中心注册自己
    fetch-registry: false # false 表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
     #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #设置与Eureka Server交互的地址 查询服务和注册服务都需要依赖这个地址
     defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7000.com:7000/eureka/
     #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka6999.com:6999/eureka/
     #defaultZone: http://eureka7000.com:7000/eureka/,http://eureka6999.com:6999/eureka/

